# Generated by Django 5.2.9 on 2026-01-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(help_text='Введите страну', max_length=100, verbose_name='Страна')),
                ('inn', models.CharField(help_text='Введите ИНН компании', max_length=20, verbose_name='ИНН')),
                ('address', models.CharField(help_text='Введите адрес', max_length=300, verbose_name='Адрес')),
                ('email', models.EmailField(blank=True, help_text='Введите email для связи', max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='Введите контактный телефон', max_length=50, null=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
